### ISSUE TITLE
The workflow does not change to amazon.se with my location set to Sweden

### ISSUE THREAD

**Issue by thehyperspacechild** [alfredapp/amazon-suggest-workflow#1]
The workflow says "To change Amazon store, set your location in Alfred's General preferences." but it seems the workflow does not recognize Swedish Amazon yet, so I see suggestions from amazon.com instead.

**Comment by vitorgalvao** [comment]
Thank you for the report. This has to be changed in Alfred itself and not the workflow. Keep an eye out on the next release!

**Comment by vitorgalvao** [comment]
Coincidentally, the old API stopped working so it’s been updated. You now pick the store in the workflow itself.

**Comment by thehyperspacechild** [comment]
Thanks for fixing it so quickly. **Much** appreciated!
